[project]
name = "weather-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anyio>=4.9.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.10.1",
    "pydantic>=2.11.7",
    "python-dotenv>=1.0.0",
]
